// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz0SAl9osh6HWF9X0BvfHDRN4rZc9IVn0',
    appId: '1:716664389545:web:75b65004f00608ac1cceb8',
    messagingSenderId: '716664389545',
    projectId: 'chatappf-8cb3c',
    authDomain: 'chatappf-8cb3c.firebaseapp.com',
    storageBucket: 'chatappf-8cb3c.firebasestorage.app',
    measurementId: 'G-GDX033ETBD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIA4ItG803RtF1VxiJ_hRNcZFntCrnUPg',
    appId: '1:716664389545:android:f46745ee7061ba361cceb8',
    messagingSenderId: '716664389545',
    projectId: 'chatappf-8cb3c',
    storageBucket: 'chatappf-8cb3c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2I42f6NEbgSsjzxXxVvTVMK6PEOOaqvs',
    appId: '1:716664389545:ios:b7147b16faeef3e31cceb8',
    messagingSenderId: '716664389545',
    projectId: 'chatappf-8cb3c',
    storageBucket: 'chatappf-8cb3c.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2I42f6NEbgSsjzxXxVvTVMK6PEOOaqvs',
    appId: '1:716664389545:ios:b7147b16faeef3e31cceb8',
    messagingSenderId: '716664389545',
    projectId: 'chatappf-8cb3c',
    storageBucket: 'chatappf-8cb3c.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAz0SAl9osh6HWF9X0BvfHDRN4rZc9IVn0',
    appId: '1:716664389545:web:94046fc923dbabf51cceb8',
    messagingSenderId: '716664389545',
    projectId: 'chatappf-8cb3c',
    authDomain: 'chatappf-8cb3c.firebaseapp.com',
    storageBucket: 'chatappf-8cb3c.firebasestorage.app',
    measurementId: 'G-KJV0ZSM30P',
  );
}
